import React, { useState, useEffect } from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { Button, Row, Col, FormText } from 'reactstrap';
import { Translate, translate, ValidatedField, ValidatedForm } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { useAppDispatch, useAppSelector } from 'app/config/store';
import { getTenant, updateTenant, createTenant } from './tenant-management.reducer';
import { getDatabaseVendors } from './database-vendor.reducer';
import { ITenant } from './tenant.model';
import { IDatabaseVendor } from './database-vendor.model';

interface AutoGeneratedFieldsProps {
  tenantKey: string;
  databaseVendorCode?: string;
  databaseVendors: IDatabaseVendor[];
}

const AutoGeneratedFields = ({ tenantKey, databaseVendorCode, databaseVendors }: AutoGeneratedFieldsProps) => {
  const vendor =
    databaseVendors.find(v => v.vendorCode === databaseVendorCode) ||
    databaseVendors.find(v => v.vendorCode === 'POSTGRESQL') ||
    databaseVendors[0];
  const dbDriverKey = vendor?.driverKey || 'postgresql';
  const dbPort = vendor?.defaultPort || 5432;
  const dbUrl =
    tenantKey && vendor?.jdbcUrlTemplate
      ? vendor.jdbcUrlTemplate.replace('{host}', 'localhost').replace('{port}', String(dbPort)).replace('{database}', `rms_${tenantKey}`)
      : tenantKey
        ? `jdbc:${dbDriverKey}://localhost:${dbPort}/rms_${tenantKey}`
        : '';

  return (
    <>
      <div className="mb-3">
        <label className="form-label">{translate('tenantManagement.subdomain')}</label>
        <input type="text" className="form-control" readOnly value={tenantKey ? `${tenantKey}.atparui.com` : ''} />
        <FormText>
          <Translate contentKey="tenantManagement.help.subdomain">Auto-generated subdomain based on tenant key</Translate>
        </FormText>
      </div>
      <h4>
        <Translate contentKey="tenantManagement.databaseConfig">Database Configuration (Auto-generated)</Translate>
      </h4>
      <div className="mb-3">
        <label className="form-label">{translate('tenantManagement.tenantId')}</label>
        <input type="text" className="form-control" readOnly value={tenantKey || ''} />
        <FormText>
          <Translate contentKey="tenantManagement.help.tenantId">Auto-generated from tenant key</Translate>
        </FormText>
      </div>
      <div className="mb-3">
        <label className="form-label">{translate('tenantManagement.databaseUrl')}</label>
        <input type="text" className="form-control" readOnly value={dbUrl} />
        <FormText>
          <Translate contentKey="tenantManagement.help.databaseUrl">Auto-generated database URL based on selected database type</Translate>
        </FormText>
      </div>
      <div className="mb-3">
        <label className="form-label">{translate('tenantManagement.databaseUsername')}</label>
        <input type="text" className="form-control" readOnly value={tenantKey ? `rms_${tenantKey}` : ''} />
        <FormText>
          <Translate contentKey="tenantManagement.help.databaseUsername">Auto-generated database user</Translate>
        </FormText>
      </div>
      <div className="mb-3">
        <label className="form-label">{translate('tenantManagement.databasePassword')}</label>
        <input type="text" className="form-control" readOnly value="Auto-generated during creation" />
        <FormText>
          <Translate contentKey="tenantManagement.help.databasePassword">Password will be auto-generated</Translate>
        </FormText>
      </div>
      <div className="mb-3">
        <label className="form-label">{translate('tenantManagement.schemaName')}</label>
        <input type="text" className="form-control" readOnly value={tenantKey ? `${tenantKey}_schema` : ''} />
        <FormText>
          <Translate contentKey="tenantManagement.help.schemaName">Auto-generated schema name</Translate>
        </FormText>
      </div>
      <h4>
        <Translate contentKey="tenantManagement.keycloakConfig">Keycloak Configuration (Auto-generated)</Translate>
      </h4>
      <div className="mb-3">
        <label className="form-label">{translate('tenantManagement.realmName')}</label>
        <input type="text" className="form-control" readOnly value={tenantKey ? `${tenantKey}_realm` : ''} />
        <FormText>
          <Translate contentKey="tenantManagement.help.realmName">Auto-generated Keycloak realm</Translate>
        </FormText>
      </div>
      <div className="mb-3">
        <label className="form-label">{translate('tenantManagement.clientId')}</label>
        <input type="text" className="form-control" readOnly value={tenantKey ? `${tenantKey}_web` : ''} />
        <FormText>
          <Translate contentKey="tenantManagement.help.clientId">Auto-generated web client ID</Translate>
        </FormText>
      </div>
      <div className="mb-3">
        <label className="form-label">Mobile Client ID</label>
        <input type="text" className="form-control" readOnly value={tenantKey ? `${tenantKey}_mobile` : ''} />
        <FormText>
          <Translate contentKey="tenantManagement.help.mobileClientId">Auto-generated mobile client ID</Translate>
        </FormText>
      </div>
      <div className="mb-3">
        <label className="form-label">{translate('tenantManagement.defaultRoles')}</label>
        <input
          type="text"
          className="form-control"
          readOnly
          value="ROLE_ADMIN,ROLE_MANAGER,ROLE_SUPERVISOR,ROLE_WAITER,ROLE_CHEF,ROLE_CASHIER,ROLE_CUSTOMER,ROLE_ANONYMOUS"
        />
        <FormText>
          <Translate contentKey="tenantManagement.help.defaultRoles">Default roles created in the realm</Translate>
        </FormText>
      </div>
    </>
  );
};

const TenantKeyField = ({ setCurrentTenantKey }: { setCurrentTenantKey: (value: string) => void }) => {
  const handleKeyDown = (e: React.KeyboardEvent<HTMLInputElement>) => {
    // Allow: backspace, delete, tab, escape, enter, and arrow keys
    if (
      [8, 9, 27, 13, 46, 37, 38, 39, 40].indexOf(e.keyCode) !== -1 ||
      // Allow: Ctrl+A, Ctrl+C, Ctrl+V, Ctrl+X
      (e.keyCode === 65 && e.ctrlKey === true) ||
      (e.keyCode === 67 && e.ctrlKey === true) ||
      (e.keyCode === 86 && e.ctrlKey === true) ||
      (e.keyCode === 88 && e.ctrlKey === true)
    ) {
      return;
    }
    // Ensure that it is a number or letter and stop the keypress
    if ((e.shiftKey || e.keyCode < 48 || e.keyCode > 57) && (e.keyCode < 65 || e.keyCode > 90)) {
      e.preventDefault();
    }
  };

  const handlePaste = (e: React.ClipboardEvent<HTMLInputElement>) => {
    // Get pasted data and filter it
    const pastedData = e.clipboardData.getData('text');
    const filteredData = pastedData.replace(/[^a-zA-Z0-9]/g, '');

    // If data was filtered, prevent default paste and insert filtered data
    if (filteredData !== pastedData) {
      e.preventDefault();
      const input = e.currentTarget;
      const start = input.selectionStart || 0;
      const end = input.selectionEnd || 0;
      const currentValue = input.value;
      const newValue = currentValue.substring(0, start) + filteredData + currentValue.substring(end);

      // Use native input value setter to trigger React Hook Form's onChange
      const nativeInputValueSetter = Object.getOwnPropertyDescriptor(window.HTMLInputElement.prototype, 'value')?.set;
      if (nativeInputValueSetter) {
        nativeInputValueSetter.call(input, newValue);
        const inputEvent = new Event('input', { bubbles: true });
        input.dispatchEvent(inputEvent);
      }

      // Update state for auto-population
      setCurrentTenantKey(newValue);

      // Update cursor position
      setTimeout(() => {
        input.setSelectionRange(start + filteredData.length, start + filteredData.length);
      }, 0);
    }
  };

  return (
    <>
      <ValidatedField
        name="tenantKey"
        label={translate('tenantManagement.tenantKey')}
        id="tenant-tenantKey"
        type="text"
        onKeyDown={handleKeyDown}
        onPaste={handlePaste}
        onInput={e => {
          // Use onInput to update state for auto-population without interfering with React Hook Form's onChange
          const target = e.currentTarget as HTMLInputElement;
          setCurrentTenantKey(target.value);
        }}
        validate={{
          required: { value: true, message: translate('entity.validation.required') },
          minLength: { value: 2, message: translate('entity.validation.minlength', { min: 2 }) },
          maxLength: { value: 50, message: translate('entity.validation.maxlength', { max: 50 }) },
          pattern: { value: /^[a-zA-Z0-9]+$/, message: 'Only alphanumeric characters allowed' },
        }}
      />
    </>
  );
};

export const TenantManagementUpdate = () => {
  const dispatch = useAppDispatch();
  const navigate = useNavigate();
  const { id } = useParams<'id'>();
  const isNew = id === undefined;
  const [currentTenantKey, setCurrentTenantKey] = useState('');
  const [selectedDatabaseVendorCode, setSelectedDatabaseVendorCode] = useState<string>('POSTGRESQL');

  const tenant = useAppSelector(state => state.tenantManagement.tenant);
  const loading = useAppSelector(state => state.tenantManagement.loading);
  const updating = useAppSelector(state => state.tenantManagement.updating);
  const updateSuccess = useAppSelector(state => state.tenantManagement.updateSuccess);
  const fieldErrors = useAppSelector(state => state.tenantManagement.fieldErrors);

  const activeDatabaseVendors = useAppSelector(state => state.databaseVendor.activeDatabaseVendors);
  const vendorsLoading = useAppSelector(state => state.databaseVendor.loading);

  // Fetch database vendors on mount
  useEffect(() => {
    dispatch(getDatabaseVendors(true));
  }, [dispatch]);

  useEffect(() => {
    if (!isNew && id) {
      dispatch(getTenant(id));
    }
  }, [isNew, id, dispatch]);

  useEffect(() => {
    if (updateSuccess) {
      navigate('/admin/tenant-management');
    }
  }, [updateSuccess, navigate]);

  useEffect(() => {
    if (tenant?.tenantKey) {
      setCurrentTenantKey(tenant.tenantKey);
    }
    if (tenant?.databaseVendorCode) {
      setSelectedDatabaseVendorCode(tenant.databaseVendorCode);
    } else if (activeDatabaseVendors.length > 0) {
      // Set default to first vendor (should be PostgreSQL)
      const defaultVendor = activeDatabaseVendors.find(v => v.vendorCode === 'POSTGRESQL') || activeDatabaseVendors[0];
      setSelectedDatabaseVendorCode(defaultVendor?.vendorCode || 'POSTGRESQL');
    }
  }, [tenant, activeDatabaseVendors]);

  const saveEntity = (values: ITenant) => {
    const vendorCode = values.databaseVendorCode || selectedDatabaseVendorCode || 'POSTGRESQL';
    const vendor = activeDatabaseVendors.find(v => v.vendorCode === vendorCode) || activeDatabaseVendors[0];
    const dbDriverKey = vendor?.driverKey || 'postgresql';
    const dbPort = vendor?.defaultPort || 5432;
    const tenantKeyValue = values.tenantKey || currentTenantKey;

    // Generate database URL using template if available, otherwise use default format
    let databaseUrl = '';
    if (vendor?.jdbcUrlTemplate && tenantKeyValue) {
      databaseUrl = vendor.jdbcUrlTemplate
        .replace('{host}', 'localhost')
        .replace('{port}', String(dbPort))
        .replace('{database}', `rms_${tenantKeyValue}`);
    } else if (tenantKeyValue) {
      databaseUrl = `jdbc:${dbDriverKey}://localhost:${dbPort}/rms_${tenantKeyValue}`;
    }

    const entity = {
      ...tenant,
      ...values,
      tenantId: tenantKeyValue,
      subdomain: tenantKeyValue ? `${tenantKeyValue}.atparui.com` : '',
      databaseVendorCode: vendorCode,
      databaseUrl: databaseUrl,
      databaseUsername: `rms_${tenantKeyValue}`,
      databasePassword: 'auto-generated',
      schemaName: `${tenantKeyValue}_schema`,
      realmName: `${tenantKeyValue}_realm`,
      clientId: `${tenantKeyValue}_web`,
    };

    // Ensure tenantKey is set from currentTenantKey if not in values
    if (!entity.tenantKey && currentTenantKey) {
      entity.tenantKey = currentTenantKey;
    }

    if (isNew) {
      dispatch(createTenant(entity));
    } else {
      dispatch(updateTenant(entity));
    }
  };

  const defaultValues = () => {
    const defaultVendorCode =
      activeDatabaseVendors.find(v => v.vendorCode === 'POSTGRESQL')?.vendorCode || activeDatabaseVendors[0]?.vendorCode || 'POSTGRESQL';
    return isNew
      ? {
          active: true,
          tenantKey: '',
          databaseVendorCode: defaultVendorCode,
          defaultRoles: 'ROLE_ADMIN,ROLE_MANAGER,ROLE_SUPERVISOR,ROLE_WAITER,ROLE_CHEF,ROLE_CASHIER,ROLE_CUSTOMER,ROLE_ANONYMOUS',
        }
      : {
          ...tenant,
          databaseVendorCode: tenant?.databaseVendorCode || defaultVendorCode,
        };
  };

  return (
    <div>
      <Row className="justify-content-center">
        <Col md="8">
          <h2 id="tenantManagementUpdateHeading" data-cy="TenantCreateUpdateHeading">
            <Translate contentKey="tenantManagement.home.createOrEditLabel">Create or edit a Tenant</Translate>
          </h2>
        </Col>
      </Row>
      <Row className="justify-content-center">
        <Col md="8">
          {loading ? (
            <p>Loading...</p>
          ) : (
            <ValidatedForm defaultValues={defaultValues()} onSubmit={saveEntity}>
              {!isNew ? (
                <ValidatedField
                  name="id"
                  required
                  readOnly
                  id="tenant-id"
                  label={translate('global.field.id')}
                  validate={{ required: true }}
                />
              ) : null}
              <h4>
                <Translate contentKey="tenantManagement.basicInfo">Basic Information</Translate>
              </h4>
              <TenantKeyField setCurrentTenantKey={setCurrentTenantKey} />
              <FormText>
                <Translate contentKey="tenantManagement.help.tenantKey">
                  Unique identifier for the tenant (alphanumeric characters only)
                </Translate>
              </FormText>
              <ValidatedField
                name="name"
                label={translate('tenantManagement.name')}
                id="tenant-name"
                type="text"
                validate={{
                  required: { value: true, message: translate('entity.validation.required') },
                  minLength: { value: 2, message: translate('entity.validation.minlength', { min: 2 }) },
                  maxLength: { value: 100, message: translate('entity.validation.maxlength', { max: 100 }) },
                }}
              />
              <ValidatedField
                name="databaseVendorCode"
                label={translate('tenantManagement.databaseVendor')}
                id="tenant-databaseVendorCode"
                type="select"
                onChange={e => {
                  const value = e.target.value;
                  setSelectedDatabaseVendorCode(value);
                }}
                validate={{
                  required: { value: true, message: translate('entity.validation.required') },
                }}
                disabled={vendorsLoading}
              >
                <option value="">{vendorsLoading ? translate('global.loading') : translate('entity.validation.select')}</option>
                {activeDatabaseVendors.map(vendor => (
                  <option key={vendor.vendorCode} value={vendor.vendorCode}>
                    {vendor.displayName} {vendor.defaultPort ? `(Port: ${vendor.defaultPort})` : ''}
                  </option>
                ))}
              </ValidatedField>
              <FormText>
                <Translate contentKey="tenantManagement.help.databaseVendor">Select the database vendor for this tenant</Translate>
              </FormText>
              <AutoGeneratedFields
                tenantKey={currentTenantKey}
                databaseVendorCode={selectedDatabaseVendorCode}
                databaseVendors={activeDatabaseVendors}
              />
              <ValidatedField name="active" label={translate('tenantManagement.active')} id="tenant-active" check type="checkbox" />
              <Button tag={Link} id="cancel-save" data-cy="entityCreateCancelButton" to="/admin/tenant-management" replace color="info">
                <FontAwesomeIcon icon="arrow-left" />
                &nbsp;
                <span className="d-none d-md-inline">
                  <Translate contentKey="entity.action.back">Back</Translate>
                </span>
              </Button>
              &nbsp;
              <Button color="primary" id="save-entity" data-cy="entityCreateSaveButton" type="submit" disabled={updating}>
                <FontAwesomeIcon icon="save" />
                &nbsp;
                <Translate contentKey="entity.action.save">Save</Translate>
              </Button>
            </ValidatedForm>
          )}
        </Col>
      </Row>
    </div>
  );
};

export default TenantManagementUpdate;
