import React, { useState, useEffect } from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Translate, translate, ValidatedField, ValidatedForm } from 'react-jhipster';
import { ArrowLeft, Save, Upload, Plug, Loader2, Database, Globe, KeyRound, User, Server, HardDrive } from 'lucide-react';

import axios from 'axios';
import { useAppDispatch, useAppSelector } from 'app/config/store';
import { getTenant, updateTenant, createTenant } from './tenant-management.reducer';
import { getDatabaseVendors } from './database-vendor.reducer';
import { getRecentVendorVersions } from './database-vendor-version.reducer';
import { getDrivers, uploadDriver } from './database-driver.reducer';
import { getActivePlatforms } from './platform.reducer';
import { ITenant } from './tenant.model';
import { IDatabaseVendor } from './database-vendor.model';
import { IDatabaseVendorVersion } from './database-vendor-version.model';
import { IDatabaseDriver } from './database-driver.model';
import { IPlatform } from './platform.model';
import { IDatabaseConnectionTest, IDatabaseConnectionTestResult } from './database-connection-test.model';

// Helper function to generate tenant key from name
const generateTenantKey = (name: string): string => {
  if (!name) return '';
  return name
    .toLowerCase()
    .trim()
    .replace(/[^a-z0-9\s-]/g, '') // Remove special characters
    .replace(/\s+/g, '-') // Replace spaces with hyphens
    .replace(/-+/g, '-') // Replace multiple hyphens with single
    .replace(/^-|-$/g, ''); // Remove leading/trailing hyphens
};

export const TenantManagementUpdate = () => {
  const dispatch = useAppDispatch();
  const navigate = useNavigate();
  const { id } = useParams<'id'>();
  const isNew = id === undefined;
  const [tenantName, setTenantName] = useState('');
  const [autoGeneratedTenantKey, setAutoGeneratedTenantKey] = useState('');
  const [selectedDatabaseVendorCode, setSelectedDatabaseVendorCode] = useState<string>('POSTGRESQL');
  const [selectedVendorId, setSelectedVendorId] = useState<number | null>(null);
  const [selectedVersionId, setSelectedVersionId] = useState<number | null>(null);
  const [selectedDriverId, setSelectedDriverId] = useState<number | null>(null);
  const [provisioningMode, setProvisioningMode] = useState<string>('AUTO_CREATE');
  const [databaseOwnershipType, setDatabaseOwnershipType] = useState<string>('PLATFORM');
  const [connectionTestResult, setConnectionTestResult] = useState<IDatabaseConnectionTestResult | null>(null);
  const [testingConnection, setTestingConnection] = useState(false);
  const [uploadingDriver, setUploadingDriver] = useState(false);
  const [driverFile, setDriverFile] = useState<File | null>(null);
  const [driverClassName, setDriverClassName] = useState<string>('');
  const [activeTab, setActiveTab] = useState('basic');

  const tenant = useAppSelector(state => state.tenantManagement.tenant);
  const loading = useAppSelector(state => state.tenantManagement.loading);
  const updating = useAppSelector(state => state.tenantManagement.updating);
  const updateSuccess = useAppSelector(state => state.tenantManagement.updateSuccess);
  const fieldErrors = useAppSelector(state => state.tenantManagement.fieldErrors);

  const activeDatabaseVendors = useAppSelector(state => state.databaseVendor.activeDatabaseVendors);
  const vendorsLoading = useAppSelector(state => state.databaseVendor.loading);
  const recentVersions = useAppSelector(state => state.databaseVendorVersion.recentVersions);
  const versionsLoading = useAppSelector(state => state.databaseVendorVersion.loading);
  const availableDrivers = useAppSelector(state => state.databaseDriver.drivers);
  const driversLoading = useAppSelector(state => state.databaseDriver.loading);
  const activePlatforms = useAppSelector(state => state.platform.activePlatforms);
  const platformsLoading = useAppSelector(state => state.platform.loading);

  // Fetch database vendors on mount
  useEffect(() => {
    dispatch(getDatabaseVendors(true));
  }, [dispatch]);

  // Fetch active platforms on mount
  useEffect(() => {
    dispatch(getActivePlatforms());
  }, [dispatch]);

  // Fetch versions when vendor changes
  useEffect(() => {
    if (selectedVendorId) {
      dispatch(getRecentVendorVersions({ vendorId: selectedVendorId, years: 3 }));
    }
  }, [selectedVendorId, dispatch]);

  // Fetch drivers when version changes
  useEffect(() => {
    if (selectedVendorId && selectedVersionId) {
      dispatch(getDrivers({ vendorId: selectedVendorId, versionId: selectedVersionId }));
    }
  }, [selectedVendorId, selectedVersionId, dispatch]);

  useEffect(() => {
    if (!isNew && id) {
      dispatch(getTenant(id));
    }
  }, [isNew, id, dispatch]);

  useEffect(() => {
    if (updateSuccess) {
      navigate('/admin/tenant-management');
    }
  }, [updateSuccess, navigate]);

  useEffect(() => {
    if (tenant?.name) {
      setTenantName(tenant.name);
      // For existing tenants, preserve the tenantKey; for new tenants, generate from name
      if (tenant.tenantKey) {
        setAutoGeneratedTenantKey(tenant.tenantKey);
      } else {
        setAutoGeneratedTenantKey(generateTenantKey(tenant.name));
      }
    } else if (tenant?.tenantKey) {
      // If we have tenantKey but no name (shouldn't happen, but handle it)
      setAutoGeneratedTenantKey(tenant.tenantKey);
    }
    if (tenant?.databaseVendorCode) {
      setSelectedDatabaseVendorCode(tenant.databaseVendorCode);
      const vendor = activeDatabaseVendors.find(v => v.vendorCode === tenant.databaseVendorCode);
      if (vendor?.id) {
        setSelectedVendorId(vendor.id);
      }
    } else if (activeDatabaseVendors.length > 0) {
      // Set default to first vendor (should be PostgreSQL)
      const defaultVendor = activeDatabaseVendors.find(v => v.vendorCode === 'POSTGRESQL') || activeDatabaseVendors[0];
      setSelectedDatabaseVendorCode(defaultVendor?.vendorCode || 'POSTGRESQL');
      if (defaultVendor?.id) {
        setSelectedVendorId(defaultVendor.id);
      }
    }
    if (tenant?.databaseVendorVersionId) {
      setSelectedVersionId(tenant.databaseVendorVersionId);
    }
    if (tenant?.databaseDriverId) {
      setSelectedDriverId(tenant.databaseDriverId);
    }
    if (tenant?.databaseProvisioningMode) {
      setProvisioningMode(tenant.databaseProvisioningMode);
    } else {
      setProvisioningMode('AUTO_CREATE');
    }
    if (tenant?.databaseOwnershipType) {
      setDatabaseOwnershipType(tenant.databaseOwnershipType);
    } else {
      setDatabaseOwnershipType('PLATFORM');
    }
    // Platform ID is already in tenant object, no need to set state
  }, [tenant, activeDatabaseVendors]);

  const testDatabaseConnection = async (values: ITenant) => {
    if (!values.databaseHost || !values.databasePort || !values.databaseName || !values.databaseUsername || !values.databasePassword) {
      setConnectionTestResult({
        success: false,
        message: 'Please fill in all connection details before testing',
      });
      return;
    }

    setTestingConnection(true);
    setConnectionTestResult(null);

    const testRequest: IDatabaseConnectionTest = {
      vendorCode: selectedDatabaseVendorCode,
      versionId: selectedVersionId || undefined,
      driverId: selectedDriverId || undefined,
      host: values.databaseHost || '',
      port: values.databasePort || 5432,
      databaseName: values.databaseName || '',
      schemaName: values.schemaName,
      username: values.databaseUsername || '',
      password: values.databasePassword || '',
    };

    try {
      const response = await axios.post<IDatabaseConnectionTestResult>('api/tenants/test-database-connection', testRequest);
      setConnectionTestResult(response.data);
    } catch (error: any) {
      setConnectionTestResult({
        success: false,
        message: error.response?.data?.message || 'Connection test failed',
        errorDetails: error.response?.data?.errorDetails || error.message,
      });
    } finally {
      setTestingConnection(false);
    }
  };

  const saveEntity = (values: ITenant) => {
    const vendorCode = values.databaseVendorCode || selectedDatabaseVendorCode || 'POSTGRESQL';
    const vendor = activeDatabaseVendors.find(v => v.vendorCode === vendorCode) || activeDatabaseVendors[0];
    // Auto-generate tenant key from name if not provided
    const tenantKeyValue = values.tenantKey || autoGeneratedTenantKey || generateTenantKey(values.name || '');

    // Determine database ownership type and provisioning mode
    const ownershipType = values.databaseOwnershipType || databaseOwnershipType || 'PLATFORM';
    const provisioningModeValue = ownershipType === 'PLATFORM' ? 'AUTO_CREATE' : 'USE_EXISTING';

    // Get platform prefix for database naming
    const selectedPlatform = activePlatforms.find(p => p.id?.toString() === values.platformId?.toString());
    const platformPrefix = selectedPlatform?.prefix?.toLowerCase() || 'rms';

    let databaseUrl = '';
    let databaseHost = '';
    let databasePort = 0;
    let databaseName = '';
    let databaseUsername = '';
    let databasePassword = '';
    let schemaName = '';

    if (ownershipType === 'BYOD') {
      // BYOD - Use existing database - get values from form
      databaseHost = values.databaseHost || '';
      databasePort = values.databasePort || vendor?.defaultPort || 5432;
      databaseName = values.databaseName || '';
      databaseUsername = values.databaseUsername || '';
      databasePassword = values.databasePassword || '';
      schemaName = values.schemaName || '';

      // Generate URL from template
      if (vendor?.jdbcUrlTemplate && databaseHost && databaseName) {
        databaseUrl = vendor.jdbcUrlTemplate
          .replace('{host}', databaseHost)
          .replace('{port}', String(databasePort))
          .replace('{database}', databaseName);

        // Add schema if provided
        if (schemaName && vendor.vendorCode === 'POSTGRESQL') {
          databaseUrl += `?currentSchema=${schemaName}`;
        } else if (schemaName && vendor.vendorCode === 'ORACLE') {
          databaseUrl += databaseUrl.includes('?') ? `&current_schema=${schemaName}` : `?current_schema=${schemaName}`;
        }
      } else if (databaseHost && databaseName) {
        // Fallback URL format
        databaseUrl = `jdbc:${vendor?.driverKey || 'postgresql'}://${databaseHost}:${databasePort}/${databaseName}`;
      }
    } else {
      // PLATFORM mode - auto-create using platform database
      // Database will be created by backend, these are placeholders
      const sanitizedKey = tenantKeyValue.replace(/-/g, '_');
      databaseHost = 'platform'; // Will be replaced by backend
      databasePort = 5432;
      databaseName = `${platformPrefix}_${sanitizedKey}`;
      databaseUsername = `${platformPrefix}_${sanitizedKey}`;
      databasePassword = 'auto-generated'; // Will be replaced by backend
      schemaName = 'public';

      // Generate URL placeholder
      databaseUrl = `jdbc:postgresql://platform:5432/${databaseName}`;
    }

    const entity = {
      ...tenant,
      ...values,
      tenantId: tenantKeyValue,
      subdomain: tenantKeyValue ? `${tenantKeyValue}.atparui.com` : '',
      databaseVendorCode: ownershipType === 'PLATFORM' ? 'POSTGRESQL' : vendorCode,
      databaseVendorVersionId: selectedVersionId || undefined,
      databaseDriverId: selectedDriverId || undefined,
      databaseOwnershipType: ownershipType,
      databaseProvisioningMode: provisioningModeValue,
      databaseHost,
      databasePort,
      databaseName,
      databaseUrl,
      databaseUsername,
      databasePassword,
      schemaName,
      realmName: `${tenantKeyValue}_realm`,
      clientId: `${tenantKeyValue}_web`,
    };

    // Ensure tenantKey is set from auto-generated value if not in values
    if (!entity.tenantKey && autoGeneratedTenantKey) {
      entity.tenantKey = autoGeneratedTenantKey;
    }

    if (isNew) {
      dispatch(createTenant(entity));
    } else {
      dispatch(updateTenant(entity));
    }
  };

  const defaultValues = () => {
    const defaultVendorCode =
      activeDatabaseVendors.find(v => v.vendorCode === 'POSTGRESQL')?.vendorCode || activeDatabaseVendors[0]?.vendorCode || 'POSTGRESQL';
    const defaultVendor = activeDatabaseVendors.find(v => v.vendorCode === defaultVendorCode) || activeDatabaseVendors[0];
    const generatedKey = tenant?.tenantKey || autoGeneratedTenantKey || (tenant?.name ? generateTenantKey(tenant.name) : '');
    return isNew
      ? {
          active: true,
          name: '',
          tenantKey: generatedKey,
          databaseVendorCode: defaultVendorCode,
          databaseProvisioningMode: 'AUTO_CREATE',
          databaseHost: 'localhost',
          databasePort: defaultVendor?.defaultPort || 5432,
          defaultRoles: 'ROLE_ADMIN,ROLE_MANAGER,ROLE_SUPERVISOR,ROLE_WAITER,ROLE_CHEF,ROLE_CASHIER,ROLE_CUSTOMER,ROLE_ANONYMOUS',
        }
      : {
          ...tenant,
          tenantKey: tenant?.tenantKey || generatedKey,
          databaseVendorCode: tenant?.databaseVendorCode || defaultVendorCode,
          databaseProvisioningMode: tenant?.databaseProvisioningMode || 'AUTO_CREATE',
          databaseHost: tenant?.databaseHost || 'localhost',
          databasePort: tenant?.databasePort || defaultVendor?.defaultPort || 5432,
        };
  };

  // Helper to get database URL preview
  const getDatabaseUrlPreview = () => {
    const vendor =
      activeDatabaseVendors.find(v => v.vendorCode === selectedDatabaseVendorCode) ||
      activeDatabaseVendors.find(v => v.vendorCode === 'POSTGRESQL') ||
      activeDatabaseVendors[0];
    const dbDriverKey = vendor?.driverKey || 'postgresql';
    const dbPort = vendor?.defaultPort || 5432;
    const tenantKey = autoGeneratedTenantKey || generateTenantKey(tenantName);
    return tenantKey && vendor?.jdbcUrlTemplate
      ? vendor.jdbcUrlTemplate.replace('{host}', 'localhost').replace('{port}', String(dbPort)).replace('{database}', `rms_${tenantKey}`)
      : tenantKey
        ? `jdbc:${dbDriverKey}://localhost:${dbPort}/rms_${tenantKey}`
        : '';
  };

  return (
    <div className="space-y-6 w-full max-w-5xl mx-auto pb-8">
      {/* Page Header */}
      <div>
        <h1 className="text-3xl font-bold tracking-tight" id="tenantManagementUpdateHeading" data-cy="TenantCreateUpdateHeading">
          <Translate contentKey="tenantManagement.home.createOrEditLabel">Create or edit a Tenant</Translate>
        </h1>
        <p className="text-muted-foreground mt-1.5">
          <Translate contentKey="tenantManagement.home.subtitle">Manage and configure tenant settings</Translate>
        </p>
      </div>

      {loading ? (
        <div className="flex items-center justify-center h-64">
          <Loader2 className="h-8 w-8 animate-spin text-muted-foreground" />
        </div>
      ) : (
        <ValidatedForm defaultValues={defaultValues()} onSubmit={saveEntity}>
          {/* Hidden field for tenantKey to ensure it's submitted */}
          <ValidatedField name="tenantKey" type="hidden" value={autoGeneratedTenantKey || generateTenantKey(tenantName)} />

          <Tabs value={activeTab} onValueChange={setActiveTab} className="w-full">
            <TabsList className="grid w-full grid-cols-4 mb-6">
              <TabsTrigger value="basic" className="flex items-center gap-2">
                <User className="h-4 w-4" />
                <span className="hidden sm:inline">Basic Details</span>
                <span className="sm:hidden">Basic</span>
              </TabsTrigger>
              <TabsTrigger value="database" className="flex items-center gap-2">
                <Database className="h-4 w-4" />
                <span className="hidden sm:inline">Database</span>
                <span className="sm:hidden">DB</span>
              </TabsTrigger>
              <TabsTrigger value="subdomain" className="flex items-center gap-2">
                <Globe className="h-4 w-4" />
                <span className="hidden sm:inline">Subdomain</span>
                <span className="sm:hidden">Domain</span>
              </TabsTrigger>
              <TabsTrigger value="keycloak" className="flex items-center gap-2">
                <KeyRound className="h-4 w-4" />
                <span className="hidden sm:inline">Keycloak</span>
                <span className="sm:hidden">Auth</span>
              </TabsTrigger>
            </TabsList>

            {/* Tab 1: Basic Details */}
            <TabsContent value="basic" className="space-y-6">
              <Card className="border-2">
                <CardHeader className="bg-muted/50 pb-4">
                  <CardTitle className="text-xl">
                    <Translate contentKey="tenantManagement.basicInfo">Basic Information</Translate>
                  </CardTitle>
                  <CardDescription>
                    <Translate contentKey="tenantManagement.help.tenantKey">Enter the basic details for the tenant</Translate>
                  </CardDescription>
                </CardHeader>
                <CardContent className="space-y-6 pt-6">
                  {/* Tenant Name - Only editable field */}
                  <div className="space-y-2">
                    <ValidatedField
                      name="name"
                      label={translate('tenantManagement.name')}
                      id="tenant-name"
                      type="text"
                      onChange={e => {
                        const nameValue = e.target.value;
                        setTenantName(nameValue);
                        // Only auto-generate tenant key for new tenants
                        if (isNew) {
                          const generatedKey = generateTenantKey(nameValue);
                          setAutoGeneratedTenantKey(generatedKey);
                        }
                      }}
                      validate={{
                        required: { value: true, message: translate('entity.validation.required') },
                        minLength: { value: 2, message: translate('entity.validation.minlength', { min: 2 }) },
                        maxLength: { value: 100, message: translate('entity.validation.maxlength', { max: 100 }) },
                      }}
                    />
                    <p className="text-sm text-muted-foreground">
                      <Translate contentKey="tenantManagement.help.name">Enter the display name for the tenant</Translate>
                    </p>
                  </div>

                  {/* Auto-generated ID and Tenant Key - Read-only display */}
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-4 pt-4 border-t">
                    {!isNew && (
                      <div className="space-y-2">
                        <Label className="text-sm font-medium text-muted-foreground">
                          {translate('global.field.id')} <span className="text-xs">(Auto-generated)</span>
                        </Label>
                        <Input type="text" readOnly value={tenant?.id || ''} className="bg-muted" />
                      </div>
                    )}
                    <div className="space-y-2">
                      <Label className="text-sm font-medium text-muted-foreground">
                        {translate('tenantManagement.tenantKey')} <span className="text-xs">(Auto-generated)</span>
                      </Label>
                      <Input
                        type="text"
                        readOnly
                        value={autoGeneratedTenantKey || generateTenantKey(tenantName)}
                        className="bg-muted font-mono text-sm"
                      />
                      <p className="text-xs text-muted-foreground">
                        <Translate contentKey="tenantManagement.help.tenantKey">Automatically generated from tenant name</Translate>
                      </p>
                    </div>
                  </div>

                  {/* Platform Selection */}
                  <div className="space-y-2 pt-4 border-t">
                    <ValidatedField
                      name="platformId"
                      label={translate('tenantManagement.platform')}
                      id="tenant-platformId"
                      type="select"
                      validate={{
                        required: { value: false, message: translate('entity.validation.required') },
                      }}
                      disabled={platformsLoading}
                    >
                      <option value="">{platformsLoading ? translate('global.loading') : translate('entity.validation.select')}</option>
                      {activePlatforms.map(platform => (
                        <option key={platform.id} value={platform.id}>
                          {platform.name}
                        </option>
                      ))}
                    </ValidatedField>
                    <p className="text-sm text-muted-foreground">
                      <Translate contentKey="tenantManagement.help.platform">Select the platform type for this tenant</Translate>
                    </p>
                  </div>

                  {/* Status */}
                  <div className="space-y-2 pt-4 border-t">
                    <ValidatedField name="active" label={translate('tenantManagement.active')} id="tenant-active" check type="checkbox" />
                    <p className="text-sm text-muted-foreground">
                      <Translate contentKey="tenantManagement.help.active">Enable or disable the tenant</Translate>
                    </p>
                  </div>
                </CardContent>
              </Card>
            </TabsContent>

            {/* Tab 2: Database Configuration */}
            <TabsContent value="database" className="space-y-6">
              {/* Database Vendor Selection */}
              <Card className="border-2">
                <CardHeader className="bg-muted/50 pb-4">
                  <CardTitle className="text-xl">
                    <Translate contentKey="tenantManagement.databaseVendor">Database Vendor</Translate>
                  </CardTitle>
                  <CardDescription>
                    <Translate contentKey="tenantManagement.help.databaseVendor">Select the database vendor for this tenant</Translate>
                  </CardDescription>
                </CardHeader>
                <CardContent className="space-y-6 pt-6">
                  <div className="space-y-2">
                    <ValidatedField
                      name="databaseVendorCode"
                      label={translate('tenantManagement.databaseVendor')}
                      id="tenant-databaseVendorCode"
                      type="select"
                      onChange={e => {
                        const value = e.target.value;
                        setSelectedDatabaseVendorCode(value);
                        const selectedVendor = activeDatabaseVendors.find(v => v.vendorCode === value);
                        if (selectedVendor?.id) {
                          setSelectedVendorId(selectedVendor.id);
                        }
                        // Reset version and driver when vendor changes
                        setSelectedVersionId(null);
                        setSelectedDriverId(null);
                        // Update port when vendor changes
                        if (selectedVendor && provisioningMode === 'USE_EXISTING') {
                          const form = document.getElementById('tenant-databasePort') as HTMLInputElement;
                          if (form) {
                            form.value = String(selectedVendor.defaultPort || 5432);
                          }
                        }
                      }}
                      validate={{
                        required: { value: true, message: translate('entity.validation.required') },
                      }}
                      disabled={vendorsLoading}
                    >
                      <option value="">{vendorsLoading ? translate('global.loading') : translate('entity.validation.select')}</option>
                      {activeDatabaseVendors.map(vendor => (
                        <option key={vendor.vendorCode} value={vendor.vendorCode}>
                          {vendor.displayName} {vendor.defaultPort ? `(Port: ${vendor.defaultPort})` : ''}
                        </option>
                      ))}
                    </ValidatedField>
                  </div>
                </CardContent>
              </Card>

              {/* Database Version & Driver */}
              {selectedVendorId && (
                <Card className="border-2">
                  <CardHeader className="bg-muted/50 pb-4">
                    <CardTitle className="text-xl">
                      <Translate contentKey="tenantManagement.databaseVersion">Database Version & Driver</Translate>
                    </CardTitle>
                    <CardDescription>
                      <Translate contentKey="tenantManagement.help.databaseVersion">Select the database version and driver</Translate>
                    </CardDescription>
                  </CardHeader>
                  <CardContent className="space-y-6 pt-6">
                    <div className="space-y-2">
                      <ValidatedField
                        name="databaseVendorVersionId"
                        label={translate('tenantManagement.databaseVersion')}
                        id="tenant-databaseVendorVersionId"
                        type="select"
                        onChange={e => {
                          const value = e.target.value ? parseInt(e.target.value, 10) : null;
                          setSelectedVersionId(value);
                          setSelectedDriverId(null); // Reset driver when version changes
                        }}
                        validate={{
                          required: { value: true, message: translate('entity.validation.required') },
                        }}
                        disabled={versionsLoading}
                      >
                        <option value="">{versionsLoading ? translate('global.loading') : translate('entity.validation.select')}</option>
                        {recentVersions.map(version => (
                          <option key={version.id} value={version.id}>
                            {version.displayName || version.version} {version.isRecommended ? '(Recommended)' : ''}
                          </option>
                        ))}
                      </ValidatedField>
                      <p className="text-sm text-muted-foreground">
                        <Translate contentKey="tenantManagement.help.databaseVersion">
                          Select the database version (showing versions from last 3 years)
                        </Translate>
                      </p>
                    </div>

                    {selectedVersionId && (
                      <div className="space-y-4 pt-4 border-t">
                        <div>
                          <h4 className="text-lg font-semibold mb-4">
                            <Translate contentKey="tenantManagement.driverManagement">Driver Management</Translate>
                          </h4>
                          <div className="space-y-2">
                            <Label>
                              <Translate contentKey="tenantManagement.uploadDriver">Upload Driver JAR</Translate>
                            </Label>
                            <Input
                              type="file"
                              accept=".jar"
                              onChange={e => {
                                const file = e.target.files?.[0];
                                setDriverFile(file || null);
                              }}
                            />
                            <p className="text-sm text-muted-foreground">
                              <Translate contentKey="tenantManagement.help.uploadDriver">
                                Upload JDBC or R2DBC driver JAR file for the selected vendor and version
                              </Translate>
                            </p>
                          </div>
                          {driverFile && (
                            <div className="space-y-4">
                              <div className="space-y-2">
                                <ValidatedField
                                  name="driverClassName"
                                  label={translate('tenantManagement.driverClassName')}
                                  id="tenant-driverClassName"
                                  type="text"
                                  value={driverClassName}
                                  onChange={e => setDriverClassName(e.target.value)}
                                  validate={{
                                    required: { value: true, message: translate('entity.validation.required') },
                                  }}
                                  placeholder="e.g., com.mysql.cj.jdbc.Driver"
                                />
                                <p className="text-sm text-muted-foreground">
                                  <Translate contentKey="tenantManagement.help.driverClassName">
                                    Full class name of the driver (e.g., com.mysql.cj.jdbc.Driver)
                                  </Translate>
                                </p>
                              </div>
                              <Button
                                variant="default"
                                onClick={async e => {
                                  e.preventDefault();
                                  if (!driverFile || !driverClassName || !selectedVendorId || !selectedVersionId) {
                                    return;
                                  }
                                  setUploadingDriver(true);
                                  const formData = new FormData();
                                  formData.append('file', driverFile);
                                  formData.append('vendorId', String(selectedVendorId));
                                  formData.append('versionId', String(selectedVersionId));
                                  formData.append('driverType', 'JDBC'); // Default to JDBC
                                  formData.append('driverClassName', driverClassName);
                                  try {
                                    const result = await dispatch(uploadDriver(formData)).unwrap();
                                    if (result && result.data && result.data.id) {
                                      setSelectedDriverId(result.data.id);
                                      setDriverFile(null);
                                      setDriverClassName('');
                                      alert('Driver uploaded successfully!');
                                      // Refresh drivers list
                                      if (selectedVendorId && selectedVersionId) {
                                        dispatch(getDrivers({ vendorId: selectedVendorId, versionId: selectedVersionId }));
                                      }
                                    }
                                  } catch (error: any) {
                                    alert('Failed to upload driver: ' + (error.message || 'Unknown error'));
                                  } finally {
                                    setUploadingDriver(false);
                                  }
                                }}
                                disabled={uploadingDriver || !driverFile || !driverClassName}
                              >
                                {uploadingDriver ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : <Upload className="mr-2 h-4 w-4" />}
                                {uploadingDriver ? (
                                  <Translate contentKey="tenantManagement.uploading">Uploading...</Translate>
                                ) : (
                                  <Translate contentKey="tenantManagement.upload">Upload Driver</Translate>
                                )}
                              </Button>
                            </div>
                          )}

                          <div className="space-y-2">
                            <ValidatedField
                              name="databaseDriverId"
                              label={translate('tenantManagement.selectDriver')}
                              id="tenant-databaseDriverId"
                              type="select"
                              onChange={e => {
                                const value = e.target.value ? parseInt(e.target.value, 10) : null;
                                setSelectedDriverId(value);
                              }}
                              disabled={driversLoading || availableDrivers.length === 0}
                            >
                              <option value="">
                                {driversLoading ? translate('global.loading') : translate('entity.validation.select')}
                              </option>
                              {availableDrivers.map(driver => (
                                <option key={driver.id} value={driver.id}>
                                  {driver.fileName} ({driver.driverType}) {driver.isDefault ? '(Default)' : ''}
                                </option>
                              ))}
                            </ValidatedField>
                            <p className="text-sm text-muted-foreground">
                              <Translate contentKey="tenantManagement.help.selectDriver">
                                Select an uploaded driver or upload a new one above
                              </Translate>
                            </p>
                          </div>
                        </div>
                      </div>
                    )}
                  </CardContent>
                </Card>
              )}

              {/* Database Ownership Type Selection */}
              <Card className="border-2">
                <CardHeader className="bg-muted/50 pb-4">
                  <CardTitle className="text-xl">
                    <Translate contentKey="tenantManagement.databaseOwnership">Database Source</Translate>
                  </CardTitle>
                  <CardDescription>Choose where to host the tenant's database</CardDescription>
                </CardHeader>
                <CardContent className="space-y-6 pt-6">
                  {/* Database Ownership Type - Visual Selection */}
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                    <div
                      className={`relative p-4 rounded-lg border-2 cursor-pointer transition-all ${
                        databaseOwnershipType === 'PLATFORM'
                          ? 'border-primary bg-primary/5 ring-2 ring-primary/20'
                          : 'border-muted hover:border-primary/50'
                      }`}
                      onClick={() => {
                        setDatabaseOwnershipType('PLATFORM');
                        setProvisioningMode('AUTO_CREATE');
                        setConnectionTestResult(null);
                      }}
                    >
                      <div className="flex items-start gap-3">
                        <div
                          className={`p-2 rounded-full ${databaseOwnershipType === 'PLATFORM' ? 'bg-primary text-primary-foreground' : 'bg-muted'}`}
                        >
                          <Server className="h-5 w-5" />
                        </div>
                        <div className="flex-1">
                          <h4 className="font-semibold">Use Platform Database</h4>
                          <p className="text-sm text-muted-foreground mt-1">
                            We'll create and manage a PostgreSQL database for you on our platform. Recommended for most users.
                          </p>
                          <ul className="text-xs text-muted-foreground mt-2 space-y-1">
                            <li>✓ Automatic backups</li>
                            <li>✓ Managed updates</li>
                            <li>✓ No setup required</li>
                          </ul>
                        </div>
                      </div>
                      {databaseOwnershipType === 'PLATFORM' && (
                        <div className="absolute top-2 right-2 bg-primary text-primary-foreground text-xs px-2 py-0.5 rounded-full">
                          Selected
                        </div>
                      )}
                    </div>

                    <div
                      className={`relative p-4 rounded-lg border-2 cursor-pointer transition-all ${
                        databaseOwnershipType === 'BYOD'
                          ? 'border-primary bg-primary/5 ring-2 ring-primary/20'
                          : 'border-muted hover:border-primary/50'
                      }`}
                      onClick={() => {
                        setDatabaseOwnershipType('BYOD');
                        setProvisioningMode('USE_EXISTING');
                        setConnectionTestResult(null);
                      }}
                    >
                      <div className="flex items-start gap-3">
                        <div
                          className={`p-2 rounded-full ${databaseOwnershipType === 'BYOD' ? 'bg-primary text-primary-foreground' : 'bg-muted'}`}
                        >
                          <HardDrive className="h-5 w-5" />
                        </div>
                        <div className="flex-1">
                          <h4 className="font-semibold">Bring Your Own Database (BYOD)</h4>
                          <p className="text-sm text-muted-foreground mt-1">
                            Connect to your existing database. For advanced users with specific requirements.
                          </p>
                          <ul className="text-xs text-muted-foreground mt-2 space-y-1">
                            <li>✓ Full control over database</li>
                            <li>✓ Support for multiple vendors</li>
                            <li>✓ Use existing infrastructure</li>
                          </ul>
                        </div>
                      </div>
                      {databaseOwnershipType === 'BYOD' && (
                        <div className="absolute top-2 right-2 bg-primary text-primary-foreground text-xs px-2 py-0.5 rounded-full">
                          Selected
                        </div>
                      )}
                    </div>
                  </div>

                  {/* Hidden field to submit ownership type */}
                  <ValidatedField name="databaseOwnershipType" type="hidden" value={databaseOwnershipType} />
                  <ValidatedField
                    name="databaseProvisioningMode"
                    type="hidden"
                    value={databaseOwnershipType === 'PLATFORM' ? 'AUTO_CREATE' : 'USE_EXISTING'}
                  />
                </CardContent>
              </Card>

              {/* BYOD - Database Connection Details */}
              {databaseOwnershipType === 'BYOD' && (
                <Card className="border-2 border-amber-200 dark:border-amber-800">
                  <CardHeader className="bg-amber-50 dark:bg-amber-900/20 pb-4">
                    <CardTitle className="text-xl flex items-center gap-2">
                      <HardDrive className="h-5 w-5" />
                      <Translate contentKey="tenantManagement.databaseConnectionDetails">Your Database Connection</Translate>
                    </CardTitle>
                    <CardDescription>Enter your existing database connection information</CardDescription>
                  </CardHeader>
                  <CardContent className="space-y-6 pt-6">
                    <div className="space-y-4">
                      <div className="space-y-2">
                        <ValidatedField
                          name="databaseHost"
                          label={translate('tenantManagement.databaseHost')}
                          id="tenant-databaseHost"
                          type="text"
                          validate={{
                            required: { value: true, message: translate('entity.validation.required') },
                          }}
                        />
                        <p className="text-sm text-muted-foreground">
                          <Translate contentKey="tenantManagement.help.databaseHost">Database server hostname or IP address</Translate>
                        </p>
                      </div>

                      <div className="space-y-2">
                        <ValidatedField
                          name="databasePort"
                          label={translate('tenantManagement.databasePort')}
                          id="tenant-databasePort"
                          type="number"
                          validate={{
                            required: { value: true, message: translate('entity.validation.required') },
                            min: { value: 1, message: 'Port must be between 1 and 65535' },
                            max: { value: 65535, message: 'Port must be between 1 and 65535' },
                          }}
                        />
                        <p className="text-sm text-muted-foreground">
                          <Translate contentKey="tenantManagement.help.databasePort">
                            Database server port (default shown based on vendor)
                          </Translate>
                        </p>
                      </div>

                      <div className="space-y-2">
                        <ValidatedField
                          name="databaseName"
                          label={translate('tenantManagement.databaseName')}
                          id="tenant-databaseName"
                          type="text"
                          validate={{
                            required: { value: true, message: translate('entity.validation.required') },
                          }}
                        />
                        <p className="text-sm text-muted-foreground">
                          <Translate contentKey="tenantManagement.help.databaseName">Name of the existing database</Translate>
                        </p>
                      </div>

                      <div className="space-y-2">
                        <ValidatedField
                          name="schemaName"
                          label={translate('tenantManagement.schemaName')}
                          id="tenant-schemaName"
                          type="text"
                        />
                        <p className="text-sm text-muted-foreground">
                          <Translate contentKey="tenantManagement.help.schemaName">
                            Schema name (optional, required for Oracle/DB2)
                          </Translate>
                        </p>
                      </div>

                      <div className="space-y-2">
                        <ValidatedField
                          name="databaseUsername"
                          label={translate('tenantManagement.databaseUsername')}
                          id="tenant-databaseUsername"
                          type="text"
                          validate={{
                            required: { value: true, message: translate('entity.validation.required') },
                          }}
                        />
                        <p className="text-sm text-muted-foreground">
                          <Translate contentKey="tenantManagement.help.databaseUsername">
                            Database user with access to the database
                          </Translate>
                        </p>
                      </div>

                      <div className="space-y-2">
                        <ValidatedField
                          name="databasePassword"
                          label={translate('tenantManagement.databasePassword')}
                          id="tenant-databasePassword"
                          type="password"
                          validate={{
                            required: { value: true, message: translate('entity.validation.required') },
                          }}
                        />
                        <p className="text-sm text-muted-foreground">
                          <Translate contentKey="tenantManagement.help.databasePassword">Password for the database user</Translate>
                        </p>
                      </div>

                      <div className="space-y-2">
                        <Button
                          variant="outline"
                          onClick={e => {
                            e.preventDefault();
                            const form = document.querySelector('form');
                            if (form instanceof HTMLFormElement) {
                              const formData = new FormData(form);
                              const values: any = {};
                              formData.forEach((value, key) => {
                                values[key] = value;
                              });
                              // Convert port to number
                              if (values.databasePort) {
                                values.databasePort = parseInt(values.databasePort, 10);
                              }
                              testDatabaseConnection(values as ITenant);
                            }
                          }}
                          disabled={testingConnection}
                        >
                          {testingConnection ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : <Plug className="mr-2 h-4 w-4" />}
                          {testingConnection ? (
                            <Translate contentKey="tenantManagement.testingConnection">Testing Connection...</Translate>
                          ) : (
                            <Translate contentKey="tenantManagement.testConnection">Test Connection</Translate>
                          )}
                        </Button>
                        {connectionTestResult && (
                          <div
                            className={`mt-2 p-3 rounded-md ${
                              connectionTestResult.success
                                ? 'bg-green-50 dark:bg-green-900/20 text-green-800 dark:text-green-200 border border-green-200 dark:border-green-800'
                                : 'bg-red-50 dark:bg-red-900/20 text-red-800 dark:text-red-200 border border-red-200 dark:border-red-800'
                            }`}
                          >
                            <div className="font-medium">
                              {connectionTestResult.success ? '✓' : '✗'} {connectionTestResult.message}
                            </div>
                            {connectionTestResult.connectionTimeMs && (
                              <div className="text-sm mt-1">Connection time: {connectionTestResult.connectionTimeMs}ms</div>
                            )}
                            {connectionTestResult.errorDetails && (
                              <div className="text-sm mt-1">
                                <strong>Details:</strong> {connectionTestResult.errorDetails}
                              </div>
                            )}
                          </div>
                        )}
                      </div>
                    </div>
                  </CardContent>
                </Card>
              )}

              {/* Platform Database - Auto-generated Preview */}
              {databaseOwnershipType === 'PLATFORM' && (
                <Card className="border-2 border-green-200 dark:border-green-800">
                  <CardHeader className="bg-green-50 dark:bg-green-900/20 pb-4">
                    <CardTitle className="text-xl flex items-center gap-2">
                      <Server className="h-5 w-5" />
                      Platform Database Preview
                    </CardTitle>
                    <CardDescription>These values will be auto-generated when the tenant is created</CardDescription>
                  </CardHeader>
                  <CardContent className="space-y-6 pt-6">
                    <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                      <div className="space-y-2">
                        <Label className="text-muted-foreground">Database Name</Label>
                        <Input
                          type="text"
                          readOnly
                          value={
                            autoGeneratedTenantKey
                              ? `${activePlatforms.find(p => p.id === tenant?.platformId)?.prefix?.toLowerCase() || 'rms'}_${autoGeneratedTenantKey.replace(/-/g, '_')}`
                              : ''
                          }
                          className="bg-muted font-mono"
                        />
                      </div>
                      <div className="space-y-2">
                        <Label className="text-muted-foreground">Database User</Label>
                        <Input
                          type="text"
                          readOnly
                          value={
                            autoGeneratedTenantKey
                              ? `${activePlatforms.find(p => p.id === tenant?.platformId)?.prefix?.toLowerCase() || 'rms'}_${autoGeneratedTenantKey.replace(/-/g, '_')}`
                              : ''
                          }
                          className="bg-muted font-mono"
                        />
                      </div>
                      <div className="space-y-2 md:col-span-2">
                        <Label className="text-muted-foreground">Database URL</Label>
                        <Input type="text" readOnly value={getDatabaseUrlPreview()} className="bg-muted font-mono text-sm" />
                      </div>
                      <div className="space-y-2">
                        <Label className="text-muted-foreground">Schema</Label>
                        <Input type="text" readOnly value="public" className="bg-muted font-mono" />
                      </div>
                      <div className="space-y-2">
                        <Label className="text-muted-foreground">Password</Label>
                        <Input type="text" readOnly value="Auto-generated (secure)" className="bg-muted" />
                      </div>
                    </div>

                    <div className="p-4 bg-green-50 dark:bg-green-900/20 rounded-lg border border-green-200 dark:border-green-800">
                      <h4 className="font-semibold text-green-800 dark:text-green-200 mb-2">What happens next?</h4>
                      <ul className="text-sm text-green-700 dark:text-green-300 space-y-1">
                        <li>• A new PostgreSQL database will be created on our platform</li>
                        <li>• A dedicated database user will be created with secure credentials</li>
                        <li>• The database schema will be initialized with required tables</li>
                        <li>• Connection details will be stored securely</li>
                      </ul>
                    </div>
                  </CardContent>
                </Card>
              )}
            </TabsContent>

            {/* Tab 3: Subdomain Configuration */}
            <TabsContent value="subdomain" className="space-y-6">
              <Card className="border-2">
                <CardHeader className="bg-muted/50 pb-4">
                  <CardTitle className="text-xl">
                    <Translate contentKey="tenantManagement.subdomain">Subdomain Configuration</Translate>
                  </CardTitle>
                  <CardDescription>
                    <Translate contentKey="tenantManagement.help.subdomain">Auto-generated subdomain based on tenant key</Translate>
                  </CardDescription>
                </CardHeader>
                <CardContent className="space-y-6 pt-6">
                  <div className="space-y-2">
                    <Label>{translate('tenantManagement.subdomain')}</Label>
                    <Input
                      type="text"
                      readOnly
                      value={autoGeneratedTenantKey ? `${autoGeneratedTenantKey}.atparui.com` : ''}
                      className="bg-muted font-mono text-lg"
                    />
                    <p className="text-sm text-muted-foreground">
                      <Translate contentKey="tenantManagement.help.subdomain">
                        This subdomain will be automatically created based on the tenant key
                      </Translate>
                    </p>
                  </div>

                  <div className="p-4 bg-blue-50 dark:bg-blue-900/20 rounded-lg border border-blue-200 dark:border-blue-800">
                    <h4 className="font-semibold text-blue-800 dark:text-blue-200 mb-2">Subdomain Information</h4>
                    <ul className="text-sm text-blue-700 dark:text-blue-300 space-y-1">
                      <li>• The subdomain is automatically generated from the tenant name</li>
                      <li>
                        • Users will access this tenant at:{' '}
                        <span className="font-mono">{autoGeneratedTenantKey || '[tenant-key]'}.atparui.com</span>
                      </li>
                      <li>• DNS configuration will be handled automatically</li>
                      <li>• SSL certificates will be provisioned for secure access</li>
                    </ul>
                  </div>
                </CardContent>
              </Card>
            </TabsContent>

            {/* Tab 4: Keycloak Configuration */}
            <TabsContent value="keycloak" className="space-y-6">
              <Card className="border-2">
                <CardHeader className="bg-muted/50 pb-4">
                  <CardTitle className="text-xl">
                    <Translate contentKey="tenantManagement.keycloakConfig">Keycloak Configuration</Translate>
                  </CardTitle>
                  <CardDescription>
                    <Translate contentKey="tenantManagement.help.clientId">
                      Auto-generated Keycloak configuration for authentication
                    </Translate>
                  </CardDescription>
                </CardHeader>
                <CardContent className="space-y-6 pt-6">
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                    <div className="space-y-2">
                      <Label>{translate('tenantManagement.realmName')}</Label>
                      <Input
                        type="text"
                        readOnly
                        value={autoGeneratedTenantKey ? `${autoGeneratedTenantKey}_realm` : ''}
                        className="bg-muted font-mono"
                      />
                      <p className="text-sm text-muted-foreground">
                        <Translate contentKey="tenantManagement.help.realmName">Auto-generated Keycloak realm</Translate>
                      </p>
                    </div>
                    <div className="space-y-2">
                      <Label>{translate('tenantManagement.clientId')}</Label>
                      <Input
                        type="text"
                        readOnly
                        value={autoGeneratedTenantKey ? `${autoGeneratedTenantKey}_web` : ''}
                        className="bg-muted font-mono"
                      />
                      <p className="text-sm text-muted-foreground">
                        <Translate contentKey="tenantManagement.help.clientId">Auto-generated web client ID</Translate>
                      </p>
                    </div>
                    <div className="space-y-2">
                      <Label>
                        <Translate contentKey="tenantManagement.mobileClientId">Mobile Client ID</Translate>
                      </Label>
                      <Input
                        type="text"
                        readOnly
                        value={autoGeneratedTenantKey ? `${autoGeneratedTenantKey}_mobile` : ''}
                        className="bg-muted font-mono"
                      />
                      <p className="text-sm text-muted-foreground">
                        <Translate contentKey="tenantManagement.help.mobileClientId">Auto-generated mobile client ID</Translate>
                      </p>
                    </div>
                  </div>

                  <div className="space-y-2 pt-4 border-t">
                    <Label>{translate('tenantManagement.defaultRoles')}</Label>
                    <Input
                      type="text"
                      readOnly
                      value="ROLE_ADMIN, ROLE_MANAGER, ROLE_SUPERVISOR, ROLE_WAITER, ROLE_CHEF, ROLE_CASHIER, ROLE_CUSTOMER, ROLE_ANONYMOUS"
                      className="bg-muted text-sm"
                    />
                    <p className="text-sm text-muted-foreground">
                      <Translate contentKey="tenantManagement.help.defaultRoles">Default roles created in the realm</Translate>
                    </p>
                  </div>

                  <div className="p-4 bg-amber-50 dark:bg-amber-900/20 rounded-lg border border-amber-200 dark:border-amber-800">
                    <h4 className="font-semibold text-amber-800 dark:text-amber-200 mb-2">Keycloak Integration</h4>
                    <ul className="text-sm text-amber-700 dark:text-amber-300 space-y-1">
                      <li>• A new Keycloak realm will be created for this tenant</li>
                      <li>• Web and mobile OAuth2 clients will be configured automatically</li>
                      <li>• Default roles will be provisioned for role-based access control</li>
                      <li>• The admin user will be notified with login credentials</li>
                    </ul>
                  </div>
                </CardContent>
              </Card>
            </TabsContent>
          </Tabs>

          {/* Form Actions - Always visible */}
          <div className="flex items-center justify-end gap-4 pt-6 border-t mt-6">
            <Button asChild id="cancel-save" data-cy="entityCreateCancelButton" variant="outline">
              <Link to="/admin/tenant-management" replace>
                <ArrowLeft className="mr-2 h-4 w-4" />
                <Translate contentKey="entity.action.back">Back</Translate>
              </Link>
            </Button>
            <Button variant="default" id="save-entity" data-cy="entityCreateSaveButton" type="submit" disabled={updating}>
              {updating ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : <Save className="mr-2 h-4 w-4" />}
              <Translate contentKey="entity.action.save">Save</Translate>
            </Button>
          </div>
        </ValidatedForm>
      )}
    </div>
  );
};

export default TenantManagementUpdate;
